### ISSUE TITLE
java.net.NoRouteToHostException: No route to host

### ISSUE THREAD

**Issue by eakteam** [hexene/LocalVPN#40]
```
E/TCPInput: Connection error: 111.13.142.2:5222:50418
    java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:742)
        at xyz.hexene.localvpn.TCPInput.processConnect(TCPInput.java:93)
        at xyz.hexene.localvpn.TCPInput.run(TCPInput.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

**Comment by DrBrad** [comment]
Has this bug been fixed?

**Comment by DrBrad** [comment]
Changing the buffer size seems to help with this bug, however you get a new error that happens less frequently.

`private static final int BUFFER_SIZE = 32767; // XXX: Is this ideal?`

New error:

`java.io.IOException: No buffer space available
    java.io.IOException: No buffer space available
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:63)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:214)
        at thesinffer.theanarch.org.thesniffer.LocalVPNService$VPNRunnable.run(LocalVPNService.java:223)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

**Comment by DrBrad** [comment]
To fix this bug change 10.0.0.2 to 192.168.0.2 for wifi.

**Comment by DrBrad** [comment]
My guess is that its due to packet sizes being too large. If you look at the TCPInput, you can see that he wrote: `// TODO: Set MSS for receiving larger packets from the device`

**Comment by mapleyuan** [comment]
@eakteam https://github.com/MambaTech-git/VPN
